---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts":
    get:
      summary: Retrieves all posts for a user
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: posts found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/definitions/post"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
